### ISSUE TITLE
Could not load type 'SitefinityWebApp.ConfigMigration'

### ISSUE THREAD

**Issue by rlee2015** [Sitefinity/db-to-filesystem-migration#1]
I did follow the following procedures.

1. Host ConfigMigration.aspx page in your application under ~/Sitefinity and integrate it in your project.
2. Navigate to ~/Sitefinity/ConfigMigration.aspx page.

Here are the error messages. 

Server Error in '/' Application.

Parser Error

Description: An error occurred during the parsing of a resource required to service this request. Please review the following specific parse error details and modify your source file appropriately. 
Parser Error Message: Could not load type 'SitefinityWebApp.ConfigMigration'.
Source Error: 

Line 1:  <%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ConfigMigration.aspx.cs" Inherits="SitefinityWebApp.ConfigMigration" %>
Line 2:  
Line 3:  <!DOCTYPE html>

Source File: /Sitefinity/ConfigMigration.aspx    Line: 1 

Please advise what is missing? Thanks.

**Comment by todorm85** [comment]
Hi rlee2015,
in order to successfully load the page, you need to include it in your project and rebuild it. I`ve updated the documentation and added that extra step. 
In visual studio in solution explorer, click the "show all files" button and then right click on the ConfigMigration.aspx and from the context menu click "Include in project". Then rebuild and load the page.
Regards,
Toshko
